### ISSUE TITLE
Game Over

### ISSUE THREAD

**Issue by TinkaGrosse** [dhebbeker/memorex-android#1]
### Expected Behaviour
After wrong chice of colour box, Game Over is displayed.

### Actual Behaviour
Level is displayed, Game returns to start screen. Later, Game Over is displayed.

### Steps to reproduce
Android 7.1.1

**Comment by dhebbeker** [comment]
Thank you very much for your issue report! :+1: 

The displayed texts in question are the "Level *x*" and "Game Over (*x*)" text notifications (currently implemented using [`Toast`][]s).

I was able to reproduce the behavior your describe on an Android platform (Android 7.1.1 on a Motorola Moto G5S device). 

### Steps to reproduce
1. Start a game.
2. (optional) press symbols in the correct sequence
3. press an incorrect symbol *within a short time* after having started the game

This is the usual use case of playing the game. In case you don't wait deliberately or play very slowly this will always be the case.

### Observed Behavior
After having pressed the incorrect symbol the start screen (without the symbols) is displayed to the user. The "Level *x*" text notification is still displayed. This message vanishes after some time followed by the "Game Over *x*" text notification, which in turn is also displayed for some time.

### Undesired Behavior
If I got the [issue][] correctly, timing is the crucial point: It is unpleasant to get the "Game Over *x*" text notification although one is ready to start the next game. @TinkaGrosse, please correct me if I am wrong.

### Preliminary root cause analysis
It seems that the text notifications to be shown to the user are queued on the some devices. As the text notifications are displayed rather long, they may be shown to the user long after the game is finished. I measured a displaying duration of about 3.8s on my usual test device.

Also, on the Android platform I usually test, the text notifications in question are not queued but interrupt each other. This way the "Game Over (*x*)" text notification does not appear to the user later than the start screen.

The undesired behavior does arise as the way multiple [`Toast`][] text notifications are shown to the user varies on Android platform implementations. This is an issue and a fix should be implemented in the app considering this variations.

[`Toast`]: https://developer.android.com/reference/android/widget/Toast.html
[issue]: https://github.com/dhebbeker/memorex-android/issues/1#issue-305552030

**Comment by dhebbeker** [comment]
@TinkaGrosse, can you please test if the version [1.0.1 beta 1][] (packed in [this `apk`](https://github.com/dhebbeker/memorex-android/releases/download/v1.0.1-beta.1/memorex-v1-0-1-beta-1.apk)) resolves this issue? In case it is not sufficient to fix that issue, it would be very helpful if you could please report:
* the observed changes of version [1.0.1 beta 1][] compared to [1.0.0][]
* what else needs to be changed in order to resolve the reported problem

[1.0.1 beta 1]: https://github.com/dhebbeker/memorex-android/releases/tag/v1.0.1-beta.1
[1.0.0]: https://github.com/dhebbeker/memorex-android/releases/tag/v1.0.0

**Comment by TinkaGrosse** [comment]
Game over is now displayed in time. 
It is still diyplayed when the game shifts back to start screen. << confusing.

Also, time between Game over and back to start screen is very short.

**Comment by dhebbeker** [comment]
Thank you for your feedback! I guess a better solution has to be implemented.
